name: WorldListTrashCan
version: ${project.version}
main: pixeltech.bluenine.blworldtrashcan.plugin.universal.WorldListTrashCanUniversalPlugin
api-version: '1.13'
folia-supported: true
author: BlueNine
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  worldlisttrashcan:
    description: WorldListTrashCan 主命令
    aliases:
      - wtc
permissions:
  WorldListTrashCan.Admin:
    description: 允许重载插件并查看调试信息
    default: op
  WorldListTrashCan.Main:
    description: 允许创建世界垃圾桶
    default: true
  WorldListTrashCan.BanGui:
    description: 打开世界黑名单 GUI
    default: true
  WorldListTrashCan.GlobalTrashOpen:
    description: 打开公共垃圾桶
    default: true
  WorldListTrashCan.GlobalTrashTakeItem:
    description: 从公共垃圾桶取出物品
    default: true
  WorldListTrashCan.GlobalTrashPutItem:
    description: 向公共垃圾桶放入物品
    default: true
  WorldListTrashCan.PersonalTrashTakeItem:
    description: 从个人垃圾桶取出物品
    default: true
  WorldListTrashCan.PersonalTrashPutItem:
    description: 向个人垃圾桶放入物品
    default: true
  WorldListTrashCan.help:
    description: 查看帮助
    default: true
  WorldListTrashCan.GlobalBan:
    description: 公共垃圾桶黑名单 GUI
    default: false
  WorldListTrashCan.Look:
    description: 查询实体类型
    default: false
  WorldListTrashCan.DropMode:
    description: 防丢弃模式
    default: true
  WorldListTrashCan.PlayerTrash:
    description: 打开个人垃圾桶
    default: true
